version: '3'

services:
  minecraft:
    build: .
    container_name: minecraft_server
    ports:
      - "25565:25565"
    volumes:
      - ./data:/minecraft/world
    environment:
      - MINECRAFT_MEM_MIN=1G
      - MINECRAFT_MEM_MAX=4G
    restart: unless-stopped
